version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

executors:
  linuxgo:
    parameters:
    working_directory: /go/src/github.com/honeycombio/honeytail
    docker:
      - image: circleci/golang:1.10

jobs:
  setup:
    executor: linuxgo
    steps:
      - run: |
          mkdir workspace
          echo $(( $CIRCLE_BUILD_NUM + 1000 )) > workspace/build_id
          cat workspace/build_id
      - persist_to_workspace:
          root: workspace
          paths:
            - build_id

  test_honeytail:
    executor: linuxgo
    steps:
      - checkout
      - run: go get -v -t -d ./...
      # turn off race detection for now
      # - run: go test -race -v ./...
      - run: go test -v ./...

  build_osx:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run: echo "export BUILD_ID=$(cat workspace/build_id)" >> $BASH_ENV
      - run: go install -ldflags "-X main.BuildID=1.${BUILD_ID}" ./...

  build_debs:
    executor: linuxgo
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run: echo "export BUILD_ID=$(cat workspace/build_id)" >> $BASH_ENV
      - run: |
          sudo apt-get -qq update
          sudo apt-get install -y build-essential rpm ruby ruby-dev
          sudo gem install fpm
      - run: |
          go install -ldflags "-X main.BuildID=1.${BUILD_ID}" ./...
          $GOPATH/bin/honeytail --write_default_config > ./honeytail.conf
          ./build-pkg.sh -v "1.${BUILD_ID}" -t deb
          ./build-pkg.sh -v "1.${BUILD_ID}" -t rpm
          # pkg-test/test.sh "1.${BUILD_ID}"
      - run: echo "finished build_debs" && find . -ls
      - run: echo "finished build_debs" && find $GOPATH/bin -ls
      - run: |
          mkdir /tmp/honeytail
          cp $GOPATH/bin/* /tmp/honeytail/
          cp ./honeytail.conf /tmp/honeytail/
          find /tmp/honeytail -ls
      - run: |
          tar -cvf /tmp/honeytail.tar /tmp/honeytail
          cp /tmp/honeytail.tar workspace/
      - persist_to_workspace:
          root: workspace
          paths:
            - honeytail.tar

  publish:
    executor: linuxgo
    steps:
      - attach_workspace:
          at: workspace
      - run: echo "export BUILD_ID=$(cat workspace/build_id)" >> $BASH_ENV

      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION

      - run: echo "in publish" && find . -ls
      - run: tar -xvf workspace/honeytail.tar
      - run: find . -ls
      - run: |
          for artifact in tmp/honeytail/*; do
            aws s3 cp $artifact s3://honeycomb-builds/honeycombio/honeytail/${BUILD_ID}/${BUILD_ID}.1/home/travis/gopath/bin/
          done

workflows:
  build:
    jobs:
      - setup
      - test_honeytail:
          requires:
            - setup
      - build_debs:
          requires:
            - test_honeytail
      # - build_osx:
      #     requires:
      #       - test_honeytail
      - publish:
          requires:
            - build_debs
            # - build_osx
          filters:
            branches:
              only: master
