version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

executors:
  linuxgo:
    parameters:
    working_directory: /go/src/github.com/honeycombio/honeytail
    docker:
      - image: circleci/golang:1.10

jobs:
  setup:
    executor: linuxgo
    steps:
      ### set up buildevents
      - run: |
          mkdir -p buildevents/bin
          date +%s > buildevents/build_start
      - run: |
          curl -L -o buildevents/bin/be https://github.com/honeycombio/buildevents/releases/latest/download/buildevents
          chmod 755 buildevents/bin/be
      - persist_to_workspace:
          root: buildevents
          paths:
            - build_start
            - bin/be
      ### set up build ID for the whole workflow using the setup build number
      - run: |
          mkdir workspace
          echo $(( $CIRCLE_BUILD_NUM + 1000 )) > workspace/build_id
          cat workspace/build_id
      - persist_to_workspace:
          root: workspace
          paths:
            - build_id
      - run:
          name: report_step
          command: buildevents/bin/be step $CIRCLE_WORKFLOW_ID setup $(cat buildevents/build_start) setup
          when: always

  test_honeytail:
    executor: linuxgo
    steps:
      - checkout
      - attach_workspace:
          at: buildevents
      - run: date +%s > buildevents/step_start
      - run: buildevents/bin/be cmd $CIRCLE_WORKFLOW_ID test_honeytail go_get -- go get -v -t -d ./...
      # turn off race detection for now
      # - run: go test -race -v ./...
      - run: buildevents/bin/be cmd $CIRCLE_WORKFLOW_ID test_honeytail go_test -- go test -v ./...
      - run:
          name: report_step
          command: buildevents/bin/be step $CIRCLE_WORKFLOW_ID test_honeytail $(cat buildevents/step_start) test_honeytail
          when: always

  build_osx:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run: echo "export BUILD_ID=$(cat workspace/build_id)" >> $BASH_ENV
      - run: go install -ldflags "-X main.BuildID=1.${BUILD_ID}" ./...

  build_debs:
    executor: linuxgo
    steps:
      - attach_workspace:
          at: buildevents
      - run: date +%s > buildevents/step_start
      - checkout
      - attach_workspace:
          at: workspace
      - run: echo "export BUILD_ID=$(cat workspace/build_id)" >> $BASH_ENV
      - run: |
          buildevents/bin/be cmd $CIRCLE_WORKFLOW_ID build_debs apt_get_update -- sudo apt-get -qq update
          buildevents/bin/be cmd $CIRCLE_WORKFLOW_ID build_debs apt_get_install -- sudo apt-get install -y build-essential rpm ruby ruby-dev
          buildevents/bin/be cmd $CIRCLE_WORKFLOW_ID build_debs gem_install -- sudo gem install fpm
      - run: |
          buildevents/bin/be cmd $CIRCLE_WORKFLOW_ID build_debs go_install -- go install -ldflags "-X main.BuildID=1.${BUILD_ID}" ./...
          $GOPATH/bin/honeytail --write_default_config > ./honeytail.conf
          buildevents/bin/be cmd $CIRCLE_WORKFLOW_ID build_debs build_deb -- ./build-pkg.sh -v "1.${BUILD_ID}" -t deb
          buildevents/bin/be cmd $CIRCLE_WORKFLOW_ID build_debs build_rpm -- ./build-pkg.sh -v "1.${BUILD_ID}" -t rpm
          # pkg-test/test.sh "1.${BUILD_ID}"
      - run: echo "finished build_debs" && find . -ls
      - run: echo "finished build_debs" && find $GOPATH/bin -ls
      - run: |
          mkdir /tmp/honeytail
          cp $GOPATH/bin/* /tmp/honeytail/
          cp ./honeytail.conf /tmp/honeytail/
          find /tmp/honeytail -ls
      - run: |
          buildevents/bin/be cmd $CIRCLE_WORKFLOW_ID build_debs tar_honeytail -- tar -cvf /tmp/honeytail.tar /tmp/honeytail
          cp /tmp/honeytail.tar workspace/
      - persist_to_workspace:
          root: workspace
          paths:
            - honeytail.tar
      - run:
          name: report_step
          command: buildevents/bin/be step $CIRCLE_WORKFLOW_ID build_debs $(cat buildevents/step_start) build_debs
          when: always

  publish:
    executor: linuxgo
    steps:
      - attach_workspace:
          at: buildevents
      - run: date +%s > buildevents/step_start
      - attach_workspace:
          at: workspace
      - run: echo "export BUILD_ID=$(cat workspace/build_id)" >> $BASH_ENV

      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION

      - run: echo "in publish" && find . -ls
      - run: tar -xvf workspace/honeytail.tar
      - run: find . -ls
      - run: |
          for artifact in tmp/honeytail/*; do
            aws s3 cp $artifact s3://honeycomb-builds/honeycombio/honeytail/${BUILD_ID}/${BUILD_ID}.1/home/travis/gopath/bin/
          done
      - run:
          name: report_step
          command: buildevents/bin/be step $CIRCLE_WORKFLOW_ID publish $(cat buildevents/step_start) publish
          when: always

  ### final submits the buildevents trace for this build
  final:
    executor: linuxgo
    steps:
      - attach_workspace:
          at: buildevents
      - run |
          BUILD_START=$(cat buildevents/build_start)
          buildevents build $CIRCLE_WORKFLOW_ID $BUILD_START success

workflows:
  build:
    jobs:
      - setup
      - test_honeytail:
          requires:
            - setup
      - build_debs:
          requires:
            - test_honeytail
      # - build_osx:
      #     requires:
      #       - test_honeytail
      - publish:
          requires:
            - build_debs
            # - build_osx
          filters:
            branches:
              only: master
      - final:
          requires:
            - publish
